`Skeleton repository <http://www.linfo.org/etc_skel.html>`_ for the madvillain
user home directory layout.

This repository provides the following file tree layout:

.. code-block:: bash

 home/
 ├── .config
 │   └── gtk-3.0
 │      └── bookmarks
 ├── Documentos
 │   ├── biblioteca
 │   │   └── piscunov-cálculo-diferencial-integral-1.pdf
 │   └── madvillain.yml
 ├── Imágenes
 │   ├── animado
 │   ├── a-publicar
 │   │   └── existence.jpg
 │   └── avatar
 │       └── doom_master.jpg
 ├── Instaladores
 │   └── firmware
 │       └── firmware-iwlwifi_20190114-2_all.deb
 ├── LICENSE
 ├── little-lab
 ├── Música
 │   └── Doombeats.pls
 ├── org
 │   └── org-cv
 ├── README.md
 ├── repos
 └── Vídeos
     ├── geeklog
     └── misc
