`Skeleton repository <http://www.linfo.org/etc_skel.html>`_ for the madvillain
user home directory layout.

This repository provides the following file tree layout:

.. code-block:: bash

 home/
 ├── .config
 │   ├── gtk-3.0
 │   │   └── bookmarks
 │   └── monitors.xml
 ├── Documentos
 │   ├── biblioteca
 │   │   └── piscunov-cálculo-diferencial-integral-1.pdf
 │   └── madvillain.yml
 ├── Imágenes
 │   ├── animado
 │   ├── a-publicar
 │   │   └── existence.jpg
 │   └── avatar
 │       └── doom_master.jpg
 ├── Instaladores
 │   └── firmware
 │       ├── firmware-iwlwifi_20161130-4_all.deb
 │       └── firmware-realtek_20161130-4_all.deb
 ├── LICENSE
 ├── little-lab
 ├── Música
 │   └── Doombots.pls
 ├── README.md
 ├── repos
 └── Vídeos
     ├── geeklog
     └── misc

